repos = [
  [ name: 'builder',
    components: [[name: 'builder']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'builder',
    tokens: [codecov: 'a4fdc4ad-75fc-4d27-8a21-463e6632d9ff'],
  ],

  [ name: 'controller',
    components: [[name: 'controller']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'controller',
    tokens: [codecov: '408e953c-2aa3-4ab9-b0fa-50a21b9ea23f'],
  ],

  [ name: 'dockerbuilder',
    components: [[name: 'dockerbuilder']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'dockerbuilder',
  ],

  [ name: 'e2e-runner',
    components: [[name: 'e2e-runner']],
    slackChannel: '#testing',
    runE2e: true,
    workflowComponent: false,
  ],

  [ name: 'fluentd',
    components: [[name: 'fluentd']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'fluentd',
  ],

  [ name: 'jenkins',
    components: [[name: 'jenkins']],
    slackChannel: '#testing',
    chart: 'jenkins',
  ],

  [ name: 'jenkins-node',
    components: [[name: 'jenkins-node']],
    slackChannel: '#testing',
    chart: 'jenkins-node',
  ],

  [ name: 'logger',
    components: [[name: 'logger']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'logger',
    tokens: [codecov: '29ee317c-c441-4f3e-9cda-06a91133fc04'],
  ],

  [ name: 'minio',
    components: [[name: 'minio']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'minio',
    tokens: [codecov: '1a0a80c3-0af3-43dd-8f3e-8e57b861ff04'],
  ],

  [ name: 'monitor',
    components: [[name: 'grafana'], [name: 'influxdb'], [name: 'telegraf']],
    slackChannel: '#workflow',
    runE2e: false,
    workflowComponent: true,
    chart: 'monitor',
  ],

  [ name: 'nsq',
    components: [[name: 'nsq']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'nsqd',
  ],

  [ name: 'postgres',
    components: [[name: 'postgres']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'database',
  ],

  [ name: 'redis',
    components: [[name: 'redis']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'redis',
  ],

  [ name: 'registry',
    components: [[name: 'registry']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'registry',
  ],

  // TODO: remove when https://github.com/deis/workflow/issues/766 is resolved
  [ name: 'registry-proxy',
    components: [[name: 'registry-proxy']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'registry-proxy',
  ],

  [ name: 'registry-token-refresher',
    components: [[name: 'registry-token-refresher']],
    slackChannel: '#workflow',
    runE2e: false,
    workflowComponent: true,
    chart: 'registry-token-refresher',
  ],

  [ name: 'router',
    components: [[name: 'router']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'router',
    tokens: [codecov: '8ed73da2-fcd4-4975-ae95-5d9ca9a0f31e'],
  ],

  [ name: 'slugbuilder',
    components: [[name: 'slugbuilder']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'slugbuilder',
  ],

  [ name: 'slugrunner',
    components: [[name: 'slugrunner']],
    slackChannel: '#workflow',
    runE2e: true,
    workflowComponent: true,
    chart: 'slugrunner',
  ],

  [ name: 'workflow',
    buildJobs: false,
    slackChannel: '#workflow',
    chart: 'workflow',
  ],

  [ name: 'workflow-cli',
    buildJobs: false,
    slackChannel: '#workflow',
  ],

  [ name: 'workflow-e2e',
    components: [[name: 'workflow-e2e']],
    slackChannel: '#testing',
    runE2e: true,
    chart: 'workflow-e2e',
  ],

  [ name: 'workflow-manager',
    components: [[name: 'workflow-manager']],
    slackChannel: '#workflow',
    runE2e: false,
    workflowComponent: true,
    chart: 'workflow-manager',
    tokens: [codecov: '84d52dfe-eb5d-4121-bdbe-1b844f97d79b'],
  ],
]

repos.each { Map repo ->
  repo.commitEnvVar = "${repo.name.toUpperCase().replaceAll('-', '_')}_SHA"

  repo.components.each { Map component ->
    component.envFile = "/tmp/\${JOB_NAME}/\${BUILD_NUMBER}/${component.name}/env.properties"
  }
}
